name: bluetoothonoff
description: A simple Flutter plugin for turning on and off Bluetooth on Android devices.
version: 0.1.1
author: Fleximex <mjw_2@hotmail.com>
homepage: https://github.com/Fleximex/BluetoothOnOff

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fleximex.bluetoothonoff
        pluginClass: BluetoothOnOffPlugin
      ios:
        pluginClass: BluetoothOnOffPlugin

